// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD5NgBtf5J2jtCUQwkDk0DVbBJCCUChbY',
    appId: '1:865681765281:web:3d31a4ab7bff4cae1691e0',
    messagingSenderId: '865681765281',
    projectId: 'flutter2ndproject',
    authDomain: 'flutter2ndproject.firebaseapp.com',
    storageBucket: 'flutter2ndproject.appspot.com',
    measurementId: 'G-S2K09NHYNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzojBRlvzeJqunu7ADWwNr2xLvUP1xzyY',
    appId: '1:865681765281:android:6ed6f8b611ec01341691e0',
    messagingSenderId: '865681765281',
    projectId: 'flutter2ndproject',
    storageBucket: 'flutter2ndproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv0SxVpBDY4SgoerInhePfNKGCct6DiaU',
    appId: '1:865681765281:ios:f3c46de0a5773c871691e0',
    messagingSenderId: '865681765281',
    projectId: 'flutter2ndproject',
    storageBucket: 'flutter2ndproject.appspot.com',
    iosBundleId: 'com.example.flutter2ndProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv0SxVpBDY4SgoerInhePfNKGCct6DiaU',
    appId: '1:865681765281:ios:05e43fc03bc67d661691e0',
    messagingSenderId: '865681765281',
    projectId: 'flutter2ndproject',
    storageBucket: 'flutter2ndproject.appspot.com',
    iosBundleId: 'com.example.flutter2ndProject.RunnerTests',
  );
}
